// Simon's playlist "Works insta" — edit freely. Format: [spotify track id, title, artist]
export const PLAYLIST_URL = 'https://open.spotify.com/playlist/4R5kN2vhmLXC08O5f17cBS';
export const TRACKS = [
  ['6EUs3FH5StArwbc07i3OYG', 'Poor Leno', 'Röyksopp'],
  ['2LD2gT7gwAurzdQDQtILds', 'Veridis Quo', 'Daft Punk'],
  ['0rbgYthugGm0YW2C0RMxYZ', 'Electricity', 'Orchestral Manoeuvres In The Dark'],
  ['0qi4b1l0eT3jpzeNHeFXDT', "Just Can't Get Enough", 'Depeche Mode'],
  ['2cGxRwrMyEAp8dEbuZaVv6', 'Instant Crush', 'Daft Punk, Julian Casablancas'],
  ['4yDCTzaFfr7YOuYKpwgidL', 'Sounds Like a Melody', 'Alphaville'],
  ['5JWPUEov2wlX7c0jhYZpeB', 'Lost In Yesterday', 'Tame Impala'],
  ['6qlqjHmx6A1yeLbAmPxdCr', 'Geräusche', 'Les Big Byrd'],
  ['4NbIe1w78zaCY3lWZa17ZI', 'Hallogallo', 'NEU!'],
  ['3a6PN6BRB8PP3ms48s7kU1', 'Empire Ants', 'Gorillaz, Little Dragon'],
  ['2zs5IwJqwQkKNnNQtkfSkf', "THAT'S THAT", 'MF DOOM'],
  ['5YaqbhEmoxSpIbdBTPG6KQ', 'The Veldt', 'deadmau5, Chris James'],
  ['4f8Mh5wuWHOsfXtzjrJB3t', 'I THINK', 'Tyler, The Creator'],
  ['34iOH7LY3vme5rQxsVILZ4', 'Love Will Tear Us Apart', 'Joy Division'],
  ['7Bz8yww6UMbTgTVLG6zbI4', 'Low Rider', 'War'],
  ['1lbNgoJ5iMrMluCyhI4OQP', 'Victory Lap', 'Fred again.., Skepta, PlaqueBoyMax'],
  ['317hcMaPmKb7WOZ20G7vJB', 'pew pew pew', 'Cleo, Academics'],
  ['0gUJlYlu4cV90iyV2gTUmr', 'On Division St', 'Nation of Language'],
  ['0yljUudXzjVcGEoYmLB17X', 'Genesis', 'Grimes'],
  ['0o15nDyr5XH7vy3MV1JK8B', 'Idol', 'Mind Enterprises'],
  ['2cmRpmO04TLaKPzmAzySYZ', 'Dance Yrself Clean', 'LCD Soundsystem'],
  ['2eNSieyqDoZMa3yOSagR4q', 'Step To My Girl', 'Souls Of Mischief'],
  ['4fpxnJGDWFxjGvLJOqPPt8', 'True Faith', 'New Order'],
  ['6u0F8YTqdUic3gMpgTcNDX', 'Major Tom (Völlig losgelöst)', 'Peter Schilling'],
  ['1YmF9PvLhIISIANoMLIYGq', 'A$AP Forever', 'A$AP Rocky, Moby'],
  ['0o73cSWmV0YJeHvzDbJDdn', 'Coffin Nails', 'MF DOOM'],
  ['0oks4FnzhNp5QPTZtoet7c', 'Giorgio by Moroder', 'Daft Punk'],
  ['7LHXQ75H9np45fqXZ1yfVn', 'Ice Machine (Lost Tapes)', 'Röyksopp, Susanne Sundfør'],
  ['3PZv9w0zbzEhqK1Pdclcqk', "Don't Let the Man Get You Down", 'Fatboy Slim'],
  ['2aJDlirz6v2a4HREki98cP', 'Glue', 'BICEP'],
  ['0cytkUZkllEce2mqaMRvlZ', 'Shadowman', 'Deki Alem'],
  ['7nhth34N8VnasDc04WNjm5', 'Dansande man', 'Page'],
  ['4whkhyXTrTgHKZzkUvdwoq', 'My Old Ways', 'Tame Impala'],
  ['2muw0f6q0ZjglTTMmQ5Vt4', 'A Little More Numb', 'Les Big Byrd'],
  ['3F4JxbEkur9ZXAtQ5GFVXB', 'Suburbia', 'Pet Shop Boys'],
  ['2vlgOAH3M8Fmo19wOjeRyw', 'Freestyler', "Bomfunk MC's"],
  ['2NRWckehPD8dwH2iXmjZeB', 'Dis kô Dis kô', 'Yin Yin'],
  ['5u67VJ8GAhnkFA1FolVhD0', 'Dark And Long (Dark Train)', 'Underworld'],
  ['3h5IFI9XHm3T4dvXcKm8Vm', 'Satisfaction Skank', 'Fatboy Slim, The Rolling Stones'],
  ['59keBu439p6EtrAWdTDwpx', 'Clubs / Put Your Hands Up (In the Air)', 'His Majesty Andre, The Black & White Brothers, Fatboy Slim'],
  ['3QceuWwcGZI00IyC5dimqo', 'La Serenissima', 'Rondò Veneziano'],
  ['1omReVeoNf8T9krEhWUhBY', 'The Safety Dance', 'Men Without Hats'],
  ['3gWZ8TJ6oIpJWQBfrUOksW', 'Brimful of Asha (Norman Cook Remix)', 'Cornershop, Norman Cook'],
  ['7LPGJhkRDEW6KopWhD8DbX', 'Roi', 'Videoclub, Adèle Castillon, Mattyeux'],
  ['1ghlpxVfPbFH2jenrv9vVw', 'Duel of the Fates', 'John Williams, London Symphony Orchestra'],
  ['0ITk3g0njX3AkzTX0RX6gK', 'From the Bughouse', 'Caesars'],
  ['5pgZpHqfv4TSomtkfGZGrG', 'Revolution 909', 'Daft Punk'],
  ['28zun60LaNlxaogHwIdyvL', 'Monument (True Electric)', 'Röyksopp, Robyn'],
  ['3VwLD5o1r0YBLkjUfgSEYg', 'Das Model', 'Kraftwerk'],
  ['0t5KYFZlzrsSyhzvAqLafd', 'Victory Celebration and End Title', 'John Williams, London Symphony Orchestra'],
  ['2VEZx7NWsZ1D0eJ4uv5Fym', 'Digital Love', 'Daft Punk'],
  ['37M8nuFfSrlKfTR0AAp7gK', 'Television Rules the Nation', 'Daft Punk'],
  ['0PV1TFUMTBrDETzW6KQulB', "93 'Til Infinity", 'Souls Of Mischief'],
  ['0en6SFmN4eaErErH126wbJ', 'What Have I Done to Deserve This?', 'Pet Shop Boys, Dusty Springfield'],
  ['02lTDOxHeXTHsdwXoz6lpC', 'In the Meantime', 'Spacehog'],
  ['5uNlgK7FEg6r9BGy12P9Sx', 'Tour de France', 'Kraftwerk'],
  ['6FY7ir6yRahEgQn0mEq73N', 'Gyöngyhajú lány', 'Gábor Presser, Anna Adamis, Omega'],
  ['4KcH1ZRV2W1q7Flq0QqC76', 'Blitzkrieg Bop', 'Ramones'],
  ['7pfNVDguZ5JJefG6B5PfGd', 'Twilight', 'Mystic Jungle'],
  ['4AxrlOlmlKducWdz18bLYB', 'Sliced Tomatoes', 'Just Brothers'],
  ['1sswIomUuznrFwryY2X51w', 'Neoperreo 2', 'Secret Society, ALIC3E, hailesession, INVESTIGATE311'],
  ['2KHRENHQzTIQ001nlP9Gdc', 'Contact', 'Daft Punk'],
  ['2bfGNzdiRa1jXZRdfssSzR', 'Dirty Harry', 'Gorillaz, Bootie Brown'],
];
